### ISSUE TITLE
http connection exceptions

### ISSUE THREAD

**Issue by tiho44** [Ypurek/pytest-analyzer#5]
we have some exceptions related to HTTP connections (RemoteDisconnected and ConnectionError). looks like analyzer was trying to make an HTTP request, but the remote server closed the connection unexpectedly. this will also interrupt execution

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\WORK_DIR\actions-runner\_work\_tool\Python\3.10.4\x64\lib\site-packages\analyzer\analyzer.py", line 150, in pytest_runtest_makereport
INTERNALERROR>     connector.update_test_status(run_id=pytest.analyzer_test_run_config.test_run_id, **request)
INTERNALERROR>   File "C:\WORK_DIR\actions-runner\_work\_tool\Python\3.10.4\x64\lib\site-packages\analyzer\connector.py", line 95, in update_test_status
INTERNALERROR>     response = self.session.post(f'***self.base_url***/api/reporter/***run_id***/testrun?api_key=***self.api_key***',
INTERNALERROR>   File "C:\WORK_DIR\actions-runner\_work\_tool\Python\3.10.4\x64\lib\site-packages\requests\sessions.py", line 637, in post
INTERNALERROR>     return self.request("POST", url, data=data, json=json, **kwargs)
INTERNALERROR>   File "C:\WORK_DIR\actions-runner\_work\_tool\Python\3.10.4\x64\lib\site-packages\requests\sessions.py", line 589, in request
INTERNALERROR>     resp = self.send(prep, **send_kwargs)
INTERNALERROR>   File "C:\WORK_DIR\actions-runner\_work\_tool\Python\3.10.4\x64\lib\site-packages\requests\sessions.py", line 703, in send
INTERNALERROR>     r = adapter.send(request, **kwargs)
INTERNALERROR>   File "C:\WORK_DIR\actions-runner\_work\_tool\Python\3.10.4\x64\lib\site-packages\requests\adapters.py", line 501, in send
INTERNALERROR>     raise ConnectionError(err, request=request)
INTERNALERROR> requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by Ypurek** [comment]
fixed in v1.3.0
